package com.iaven.pojo.table;

import java.util.Date;

public class Transunit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transunit.transunitId
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    private Integer transunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transunit.name
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transunit.contactemail
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    private String contactemail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transunit.Registrationtime
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    private Date registrationtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transunit.transunitId
     *
     * @return the value of transunit.transunitId
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public Integer getTransunitid() {
        return transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transunit.transunitId
     *
     * @param transunitid the value for transunit.transunitId
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public void setTransunitid(Integer transunitid) {
        this.transunitid = transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transunit.name
     *
     * @return the value of transunit.name
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transunit.name
     *
     * @param name the value for transunit.name
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transunit.contactemail
     *
     * @return the value of transunit.contactemail
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public String getContactemail() {
        return contactemail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transunit.contactemail
     *
     * @param contactemail the value for transunit.contactemail
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public void setContactemail(String contactemail) {
        this.contactemail = contactemail == null ? null : contactemail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transunit.Registrationtime
     *
     * @return the value of transunit.Registrationtime
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public Date getRegistrationtime() {
        return registrationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transunit.Registrationtime
     *
     * @param registrationtime the value for transunit.Registrationtime
     *
     * @mbggenerated Tue Jun 13 21:38:00 CST 2023
     */
    public void setRegistrationtime(Date registrationtime) {
        this.registrationtime = registrationtime;
    }
}