server:
  port: 8710

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

feign:
  ribbon:
    ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
    ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间



spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: service_1
          uri: lb://jwtService
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1

        - id: service_2
          uri: lb://userservice
          predicates:
            - Path=/account/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter #请求数限流 名字不能随便写
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
      discovery:
        locator:
          enabled: true # 设置为true 请求路径前可以添加微服务名称 表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，# 这个router将以服务名开头的请求路径转发到对应的服务
          lower-case-service-id: true # 允许为小写


  redis:
    host: 8.130.83.55
    password: 123456
    port: 6379
    database: 10
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0
