server:
  port: 8704

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/


spring:
  application:
    name: jwtService

feign:
  ribbon:
    ReadTimeout: 6000 #建立连接所用的时间，适用于网络状况正常的情况下，两端两端连接所用的时间
    ConnectionTimeout: 6000 #建立连接后，服务器读取到可用资源的时间
  circuitbreaker:
    enabled: true

app:
  jwtSecret: shipSecretKey
  jwtExpirationMs: 86400000 # 24分钟

resilience4j.circuitbreaker:
  instances:
    backendA:
      registerHealthIndicator: true
      slidingWindowSize: 100


resilience4j.thread-pool-bulkhead:
  instances:
    backendA:
      # 配置最大线程数
      maxThreadPoolSize: 1
      # 核心线程数
      coreThreadPoolSize: 1
      #配置的队列的容量
      queueCapacity: 10
      #空闲线程的等待时间
      keepAliveDuration: 10

resilience4j.bulkhead:
  instances:
    backendB:
      maxConcurrentCalls: 10 #最大并发请求量


#resilience4j.circuitbreaker:
#  configs: #通用配置
#    default: # 断路器系统默认配置
#      #失败率，错误率达到或高于该值则进入open状态
#      failureRateThreshold: 50
#      #慢调用阀值，请求执行的时间大于该值时会标记为慢调用
#      slowCallDurationThreshold: 60s
#      #慢调用熔断阀值，当慢调用率达到或高于该值时，进入open状态
#      slowCallRateThreshold: 100
#      #状态滚动收集器大小，close状态时收集多少请求状态，用于计算失败率。
#      slidingWindowSize: 100
#      #状态收集器类型
#      #COUNT_BASED：根据数量计算，slidingWindowSize为次数
#      #TIME_BASED：根据时间计算，slidingWindowSize为秒数
#      slidingWindowType: COUNT_BASED
#      #计算错误率的最小请求数，不足最小调用次数不会触发任何变化。
#      minimumNumberOfCalls: 10
#      #是否自动进入halfOpen状态，默认false-一定时间后进入halfopen，ture-需要通过接口执行。
#      automaticTransitionFromOpenToHalfOpenEnabled: false
#      #进入halfOpen状态时，可以被调用次数，就算这些请求的失败率，低于设置的失败率变为close状态，否则变为open。
#      permittedNumberOfCallsInHalfOpenState: 10
#      #open状态变为half状态需要等待的时间，即熔断多久后开始尝试访问被熔断的服务。
#      waitDurationInOpenState: 60s
#      #事件缓冲区大小？？
#      eventConsumerBufferSize: 10
#      #被计为失败的异常集合，默认情况下所有异常都为失败。
#      recordExceptions:
#      - java.lang.Exception
#      #不会被计为失败的异常集合，优先级高于recordExceptions。
#      ignoreExceptions:
#      - java.lang.IllegalStateException
#  instances: #熔断器类型
#    aCustomizer: #使用默认配置
#      baseConfig: default
#    cacheCustomizer: #自定义配置
#      failureRateThreshold: 10