server:
  port: 8705

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8700/eureka/

spring:
  application:
    name: userservice


  datasource:
    url: jdbc:mysql://localhost:3306/shipp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
#    password: zlg%wares-manager%1006
    password: 123456
    # driver-class-name: com.mysql.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

  redis:
    host: localhost
    password: 123456
    port: 6379
    database: 0
    timeout: 1800000
    lettuce:
      pool:
        max-active: 20
        max-idle: 5
        min-idle: 0

  mail:
    host: smtp.qq.com #发送邮件服务器
    username:  1245325661@qq.com #发送邮件的邮箱地址
    password:  tcflcazgcasuihia  #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1245325661@qq.com  # 发送邮件的地址，和上面username一致

    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8



# mybatis配置
mybatis:
  mapper-locations: classpath:com/iaven/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.iaven.pojo.table    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true