package com.yufop.tran.pojo.table;

import java.util.Date;

public class Order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.id
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.transunitid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Integer transunitid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.userid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.createtime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.setout
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String setout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.destination
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String destination;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.type
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.esttime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Date esttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.state
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.weight
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private Double weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sendphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String sendphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String recphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sendname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String sendname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String recname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.content
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.sendaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String sendaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.recaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String recaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order.goodname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    private String goodname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.id
     *
     * @return the value of order.id
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.id
     *
     * @param id the value for order.id
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.transunitid
     *
     * @return the value of order.transunitid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Integer getTransunitid() {
        return transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.transunitid
     *
     * @param transunitid the value for order.transunitid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setTransunitid(Integer transunitid) {
        this.transunitid = transunitid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.userid
     *
     * @return the value of order.userid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.userid
     *
     * @param userid the value for order.userid
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.createtime
     *
     * @return the value of order.createtime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.createtime
     *
     * @param createtime the value for order.createtime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.setout
     *
     * @return the value of order.setout
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getSetout() {
        return setout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.setout
     *
     * @param setout the value for order.setout
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setSetout(String setout) {
        this.setout = setout == null ? null : setout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.destination
     *
     * @return the value of order.destination
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.destination
     *
     * @param destination the value for order.destination
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setDestination(String destination) {
        this.destination = destination == null ? null : destination.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.type
     *
     * @return the value of order.type
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.type
     *
     * @param type the value for order.type
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.esttime
     *
     * @return the value of order.esttime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Date getEsttime() {
        return esttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.esttime
     *
     * @param esttime the value for order.esttime
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setEsttime(Date esttime) {
        this.esttime = esttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.state
     *
     * @return the value of order.state
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.state
     *
     * @param state the value for order.state
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.weight
     *
     * @return the value of order.weight
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public Double getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.weight
     *
     * @param weight the value for order.weight
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setWeight(Double weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sendphone
     *
     * @return the value of order.sendphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getSendphone() {
        return sendphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sendphone
     *
     * @param sendphone the value for order.sendphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setSendphone(String sendphone) {
        this.sendphone = sendphone == null ? null : sendphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recphone
     *
     * @return the value of order.recphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getRecphone() {
        return recphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recphone
     *
     * @param recphone the value for order.recphone
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setRecphone(String recphone) {
        this.recphone = recphone == null ? null : recphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sendname
     *
     * @return the value of order.sendname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getSendname() {
        return sendname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sendname
     *
     * @param sendname the value for order.sendname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setSendname(String sendname) {
        this.sendname = sendname == null ? null : sendname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recname
     *
     * @return the value of order.recname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getRecname() {
        return recname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recname
     *
     * @param recname the value for order.recname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setRecname(String recname) {
        this.recname = recname == null ? null : recname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.content
     *
     * @return the value of order.content
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.content
     *
     * @param content the value for order.content
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.sendaddress
     *
     * @return the value of order.sendaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getSendaddress() {
        return sendaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.sendaddress
     *
     * @param sendaddress the value for order.sendaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setSendaddress(String sendaddress) {
        this.sendaddress = sendaddress == null ? null : sendaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.recaddress
     *
     * @return the value of order.recaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getRecaddress() {
        return recaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.recaddress
     *
     * @param recaddress the value for order.recaddress
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setRecaddress(String recaddress) {
        this.recaddress = recaddress == null ? null : recaddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order.goodname
     *
     * @return the value of order.goodname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public String getGoodname() {
        return goodname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order.goodname
     *
     * @param goodname the value for order.goodname
     *
     * @mbggenerated Tue Jun 13 21:37:30 CST 2023
     */
    public void setGoodname(String goodname) {
        this.goodname = goodname == null ? null : goodname.trim();
    }
}