#开发环境配置

# 数据源
spring:
  datasource:
    url: jdbc:mysql://8.130.83.55:3306/shipp?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: iaven
    password: zlg%wares-manager%1006

    driver-class-name: com.mysql.jdbc.Driver
    dbcp2:
      min-idle: 5                                # 数据库连接池的最小维持连接数
      initial-size: 5                            # 初始化连接数
      max-total: 5                               # 最大连接数
      max-wait-millis: 150                       # 等待连接获取的最大超时时间

# mybatis配置
mybatis:
  mapper-locations:classpath: com/yufop/tran/mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.yufop.tran.pojo    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
    map-underscore-to-camel-case: true


